[0m00:11:57.055196 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x706f48f3b6d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x706f4728e860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x706f4728e800>]}


============================== 00:11:57.058004 | 9cf88aa5-a16e-4979-824f-b0cdca526c97 ==============================
[0m00:11:57.058004 [info ] [MainThread]: Running with dbt=1.8.5
[0m00:11:57.058819 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/home/codespace/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt init', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m00:12:30.516078 [debug] [MainThread]: Starter project path: /usr/local/python/3.10.13/lib/python3.10/site-packages/dbt/include/starter_project
[0m00:12:30.520810 [info ] [MainThread]: 
Your new dbt project "myproject" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m00:12:30.522160 [info ] [MainThread]: Setting up your profile.
[0m00:15:42.680959 [info ] [MainThread]: Profile myproject written to /home/codespace/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m00:15:42.682317 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 225.6865, "process_user_time": 1.834224, "process_kernel_time": 0.186708, "process_mem_max_rss": "147644", "process_out_blocks": "88", "process_in_blocks": "0"}
[0m00:15:42.683224 [debug] [MainThread]: Command `dbt init` succeeded at 00:15:42.683103 after 225.69 seconds
[0m00:15:42.683857 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x706f48f3b6d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x706f4728fbe0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x706f4728ed10>]}
[0m00:15:42.684761 [debug] [MainThread]: Flushing usage events
[0m00:16:36.581946 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7073e7eb7820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7073e647e9b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7073e647e950>]}


============================== 00:16:36.584816 | f80b8429-f029-4cf1-b4e1-0b750c3d6317 ==============================
[0m00:16:36.584816 [info ] [MainThread]: Running with dbt=1.8.5
[0m00:16:36.585876 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/home/codespace/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m00:16:36.617518 [info ] [MainThread]: dbt version: 1.8.5
[0m00:16:36.618617 [info ] [MainThread]: python version: 3.10.13
[0m00:16:36.619601 [info ] [MainThread]: python path: /usr/local/python/3.10.13/bin/python3
[0m00:16:36.620589 [info ] [MainThread]: os info: Linux-6.5.0-1022-azure-x86_64-with-glibc2.31
[0m00:16:37.138259 [info ] [MainThread]: Using profiles dir at /home/codespace/.dbt
[0m00:16:37.138988 [info ] [MainThread]: Using profiles.yml file at /home/codespace/.dbt/profiles.yml
[0m00:16:37.139606 [info ] [MainThread]: Using dbt_project.yml file at /workspaces/snowdbtrep/dbt_project.yml
[0m00:16:37.140387 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m00:16:37.141420 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.6191099, "process_user_time": 1.872532, "process_kernel_time": 0.180051, "process_mem_max_rss": "148496", "process_out_blocks": "16", "command_success": false, "process_in_blocks": "0"}
[0m00:16:37.142176 [debug] [MainThread]: Command `dbt debug` failed at 00:16:37.142058 after 0.62 seconds
[0m00:16:37.142743 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7073e7eb7820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7073e648abc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7073e644b610>]}
[0m00:16:37.143327 [debug] [MainThread]: Flushing usage events
[0m17:22:42.694713 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75b488a3b760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75b486feaa10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75b486fea9b0>]}


============================== 17:22:42.700538 | b42b1014-2d47-4f30-a7e8-7c4082ac752e ==============================
[0m17:22:42.700538 [info ] [MainThread]: Running with dbt=1.8.5
[0m17:22:42.701492 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/codespace/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:22:42.702301 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/snowdbtrep/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:22:42.703539 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.07023148, "process_user_time": 1.405832, "process_kernel_time": 0.135405, "process_mem_max_rss": "85164", "process_in_blocks": "160", "process_out_blocks": "8", "command_success": false}
[0m17:22:42.704304 [debug] [MainThread]: Command `dbt run` failed at 17:22:42.704184 after 0.07 seconds
[0m17:22:42.704891 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75b488a3b760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75b486feaaa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x75b486fea9e0>]}
[0m17:22:42.705490 [debug] [MainThread]: Flushing usage events
[0m17:24:41.083805 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78978d1c77c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78978b532bc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78978b5322c0>]}


============================== 17:24:41.086832 | 28f1b0cf-b516-4932-827e-de1e630d8469 ==============================
[0m17:24:41.086832 [info ] [MainThread]: Running with dbt=1.8.5
[0m17:24:41.087781 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/home/codespace/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m17:24:41.088547 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/snowdbtrep/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:24:41.089689 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.06603966, "process_user_time": 1.404614, "process_kernel_time": 0.115393, "process_mem_max_rss": "85152", "process_out_blocks": "8", "command_success": false, "process_in_blocks": "0"}
[0m17:24:41.090468 [debug] [MainThread]: Command `dbt run` failed at 17:24:41.090335 after 0.07 seconds
[0m17:24:41.091051 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78978d1c77c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78978b533580>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x78978b5322c0>]}
[0m17:24:41.091633 [debug] [MainThread]: Flushing usage events
[0m17:25:38.149147 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72ce0537f7f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72ce036b82e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72ce036b9ff0>]}


============================== 17:25:38.152077 | 717ebc99-9277-48e6-95fb-2276f3eeb8c8 ==============================
[0m17:25:38.152077 [info ] [MainThread]: Running with dbt=1.8.5
[0m17:25:38.152965 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/codespace/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:25:38.153744 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/snowdbtrep/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:25:38.154817 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.065323874, "process_user_time": 1.417305, "process_kernel_time": 0.127398, "process_mem_max_rss": "85008", "process_out_blocks": "16", "command_success": false, "process_in_blocks": "0"}
[0m17:25:38.155549 [debug] [MainThread]: Command `dbt run` failed at 17:25:38.155433 after 0.07 seconds
[0m17:25:38.156118 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72ce0537f7f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72ce036baef0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72ce036b9750>]}
[0m17:25:38.156690 [debug] [MainThread]: Flushing usage events
